### ISSUE TITLE
大佬，请教个问题：服务端和客户端不在同一个网段时，任务执行超过15分钟后，连接会被防火墙掐断。

### ISSUE THREAD

**Issue by Bigbigtrees** [jobxhub/JobX#42]
2019-11-28 11:52:20 [ERROR]-[com.jobxhub.rpc.RpcFuture] [JobX]callback done invoke error .host:10.205.196.52:1577,action:KILL:,caught:{}
java.lang.NullPointerException
        at com.jobxhub.server.service.ExecuteService.printLog(ExecuteService.java:426)
        at com.jobxhub.server.service.ExecuteService.access$700(ExecuteService.java:48)
        at com.jobxhub.server.service.ExecuteService$KillCallback.done(ExecuteService.java:511)
        at com.jobxhub.rpc.RpcFuture.invokeCallback(RpcFuture.java:172)
        at com.jobxhub.rpc.RpcFuture.doReceived(RpcFuture.java:132)
        at com.jobxhub.rpc.RpcFuture.received(RpcFuture.java:110)
        at com.jobxhub.rpc.netty.NettyClientHandler.channelRead0(NettyClientHandler.java:88)
        at com.jobxhub.rpc.netty.NettyClientHandler.channelRead0(NettyClientHandler.java:36)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Bigbigtrees** [comment]
同网段多久都可以。不同网段15分钟以内也没问题。请问有什么思路可以追踪这个问题，请教。

**Comment by wolfboys** [comment]
请加我微信wolfboys



---原始邮件---
发件人: "Bigbigtrees"<notifications@github.com&gt;
发送时间: 2019年12月30日(周一) 上午10:18
收件人: "jobxhub/JobX"<JobX@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [jobxhub/JobX] 大佬，请教个问题：服务端和客户端不在同一个网段时，任务执行超过15分钟后，连接会被防火墙掐断。 (#42)



2019-11-28 11:52:20 [ERROR]-[com.jobxhub.rpc.RpcFuture] [JobX]callback done invoke error .host:10.205.196.52:1577,action:KILL:,caught:{}
 java.lang.NullPointerException
 at com.jobxhub.server.service.ExecuteService.printLog(ExecuteService.java:426)
 at com.jobxhub.server.service.ExecuteService.access$700(ExecuteService.java:48)
 at com.jobxhub.server.service.ExecuteService$KillCallback.done(ExecuteService.java:511)
 at com.jobxhub.rpc.RpcFuture.invokeCallback(RpcFuture.java:172)
 at com.jobxhub.rpc.RpcFuture.doReceived(RpcFuture.java:132)
 at com.jobxhub.rpc.RpcFuture.received(RpcFuture.java:110)
 at com.jobxhub.rpc.netty.NettyClientHandler.channelRead0(NettyClientHandler.java:88)
 at com.jobxhub.rpc.netty.NettyClientHandler.channelRead0(NettyClientHandler.java:36)
 at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
 at java.lang.Thread.run(Thread.java:748)
